export const ADMIN_ACCOUNT = {
  username: "admin",
  password: "admin123",
};

export const USER_ACCOUNT = {
  username: "user",
  password: "user123",
};

export const INSTRUCTOR_NAMES = [
  "Rohan Mehta",
  "Priya Nair",
  "Meera Iyer",
  "Kabir Khan",
];

export const INITIAL_INSTRUCTORS = [
  {
    id: 1,
    name: "Priya Nair",
    username: "priya.nair",
    password: "priya123",
    gender: "Female",
    phone: "9820012345",
    email: "priya.nair@yogaonlive.com",
    meetLink: "https://meet.google.com/pri-yano-ga1",
    zoomLink: "https://zoom.us/j/9820012345",
    language: "English",
    medium: "English",
    availabilitySchedule: "Daily: 7:00 am – 11:00 am, 5:00 pm – 8:30 pm IST",
    availableSlots: [
      "7:00 am - 8:00 am IST",
      "8:00 am - 9:00 am IST",
      "9:00 am - 10:00 am IST",
      "10:00 am - 11:00 am IST",
      "5:00 pm - 6:00 pm IST",
      "6:30 pm - 7:30 pm IST",
      "7:30 pm - 8:30 pm IST",
    ],
    assignedClasses: ["Morning Hatha Flow (7:00-8:00 am IST)"],
    profileImage: "",
    bio: "Certified Ashtanga & Vinyasa teacher with 8+ years experience. Specializes in alignment, prenatal modifications, and breathwork.",
    createdAt: "2026-01-10",
  },
  {
    id: 2,
    name: "Rohan Mehta",
    username: "rohan.mehta",
    password: "rohan123",
    gender: "Male",
    phone: "9819023456",
    email: "rohan.mehta@yogaonlive.com",
    meetLink: "https://meet.google.com/roh-anme-hta2",
    zoomLink: "https://zoom.us/j/9819023456",
    language: "Hindi",
    medium: "Hindi",
    availabilitySchedule: "Daily: 5:00 am – 11:30 am, 4:00 pm – 8:00 pm IST",
    availableSlots: [
      "5:00 am - 6:00 am IST",
      "6:00 am - 7:00 am IST",
      "8:00 am - 9:00 am IST",
      "9:00 am - 10:00 am IST",
      "10:30 am - 11:30 am IST",
      "4:00 pm - 5:00 pm IST",
      "5:00 pm - 6:00 pm IST",
      "7:00 pm - 8:00 pm IST",
    ],
    assignedClasses: ["Pranayama & Spine Alignment (8:00-9:00 am IST)"],
    profileImage: "",
    bio: "Traditional Hatha Yoga and Pranayama expert. Focuses on physical endurance, joint mobility, and spine health.",
    createdAt: "2026-01-15",
  },
  {
    id: 3,
    name: "Meera Iyer",
    username: "meera.iyer",
    password: "meera123",
    gender: "Female",
    phone: "9833034567",
    email: "meera.iyer@yogaonlive.com",
    meetLink: "https://meet.google.com/mee-raiy-er3",
    zoomLink: "https://zoom.us/j/9833034567",
    language: "Hindi",
    medium: "Hindi",
    availabilitySchedule: "Daily: 6:00 am – 10:00 am, 4:00 pm – 8:00 pm IST",
    availableSlots: [
      "6:00 am - 7:00 am IST",
      "8:00 am - 9:00 am IST",
      "9:00 am - 10:00 am IST",
      "10:30 am - 11:30 am IST",
      "4:00 pm - 5:00 pm IST",
      "6:00 pm - 7:00 pm IST",
      "7:00 pm - 8:00 pm IST",
    ],
    assignedClasses: ["Evening Therapeutic Restorative (6:00-7:00 pm IST)"],
    profileImage: "",
    bio: "Therapeutic yoga practitioner specializing in stress reduction, corporate wellness, and flexibility training.",
    createdAt: "2026-02-01",
  },
  {
    id: 4,
    name: "Kabir Khan",
    username: "kabir.khan",
    password: "kabir123",
    gender: "Male",
    phone: "9844045678",
    email: "kabir.khan@yogaonlive.com",
    meetLink: "https://meet.google.com/kab-irkh-an4",
    zoomLink: "https://zoom.us/j/9844045678",
    language: "English",
    medium: "English",
    availabilitySchedule: "Daily: 6:00 am – 10:30 am, 6:00 pm – 9:00 pm IST",
    availableSlots: [
      "6:00 am - 7:00 am IST",
      "7:00 am - 8:00 am IST",
      "8:00 am - 9:00 am IST",
      "6:00 pm - 7:00 pm IST",
      "6:30 pm - 7:30 pm IST",
      "7:00 pm - 8:00 pm IST",
      "7:30 pm - 8:30 pm IST",
    ],
    assignedClasses: ["Dynamic Power Vinyasa (7:00-8:00 pm IST)"],
    profileImage: "",
    bio: "Power Yoga and functional movement instructor. Passionate about core strength, calisthenics mobility, and athletic balance.",
    createdAt: "2026-02-20",
  },
];

export const TIME_SLOT_OPTIONS = [
  "5:00-6:00 am",
  "5:30-6:30 am",
  "6:00-7:00 am",
  "6:30-7:30 am",
  "7:00-8:00 am",
  "7:30-8:30 am",
  "8:00-9:00 am",
  "8:30-9:30 am",
  "9:00-10:00 am",
  "9:30-10:30 am",
  "10:00-11:00 am",
  "10:30-11:30 am",
  "11:00 am-12:00 pm",
  "11:30 am-12:30 pm",
  "12:00-1:00 pm",
  "4:00-5:00 pm",
  "4:30-5:30 pm",
  "5:00-6:00 pm",
  "5:30-6:30 pm",
  "6:00-7:00 pm",
  "6:30-7:30 pm",
  "7:00-8:00 pm",
  "7:30-8:30 pm",
  "8:00-9:00 pm",
  "8:30-9:30 pm",
  "9:00-10:00 pm",
];

export function normalizeTimeSlot(slot) {
  if (!slot) return "6:00-7:00 am";
  const str = String(slot).trim();
  const map = {
    "5:00 AM": "5:00-6:00 am",
    "5:30 AM": "5:30-6:30 am",
    "6:00 AM": "6:00-7:00 am",
    "6:30 AM": "6:30-7:30 am",
    "7:00 AM": "7:00-8:00 am",
    "7:30 AM": "7:30-8:30 am",
    "8:00 AM": "8:00-9:00 am",
    "8:30 AM": "8:30-9:30 am",
    "9:00 AM": "9:00-10:00 am",
    "9:30 AM": "9:30-10:30 am",
    "10:00 AM": "10:00-11:00 am",
    "10:30 AM": "10:30-11:30 am",
    "11:00 AM": "11:00 am-12:00 pm",
    "11:30 AM": "11:30 am-12:30 pm",
    "12:00 PM": "12:00-1:00 pm",
    "4:00 PM": "4:00-5:00 pm",
    "4:30 PM": "4:30-5:30 pm",
    "5:00 PM": "5:00-6:00 pm",
    "5:30 PM": "5:30-6:30 pm",
    "6:00 PM": "6:00-7:00 pm",
    "6:30 PM": "6:30-7:30 pm",
    "7:00 PM": "7:00-8:00 pm",
    "7:30 PM": "7:30-8:30 pm",
    "8:00 PM": "8:00-9:00 pm",
    "8:30 PM": "8:30-9:30 pm",
    "9:00 PM": "9:00-10:00 pm",
  };
  return map[str] || str;
}

export const INITIAL_CLASSES = [
  {
    id: 1,
    title: "Morning Hatha Flow",
    timeSlot: "7:00-8:00 am",
    days: ["Mon", "Wed", "Fri"],
    instructorId: 1,
    instructorName: "Priya Nair",
    classType: "group",
    meetingLink: "https://zoom.us/j/9820012345",
    language: "English",
    medium: "English",
    maxCapacity: 15,
    notes: "Gentle breathwork followed by classic Surya Namaskar sequences.",
    status: "assigned",
  },
  {
    id: 2,
    title: "Pranayama & Spine Alignment",
    timeSlot: "8:00-9:00 am",
    days: ["Tue", "Thu", "Sat"],
    instructorId: 2,
    instructorName: "Rohan Mehta",
    classType: "group",
    meetingLink: "https://zoom.us/j/9819023456",
    language: "Hindi",
    medium: "Hindi",
    maxCapacity: 20,
    notes: "Deep restorative breathing and functional core postural stabilization.",
    status: "assigned",
  },
  {
    id: 3,
    title: "Evening Therapeutic Restorative",
    timeSlot: "6:00-7:00 pm",
    days: ["Mon", "Wed", "Fri"],
    instructorId: 3,
    instructorName: "Meera Iyer",
    classType: "group",
    meetingLink: "https://zoom.us/j/9833034567",
    language: "Hindi",
    medium: "Hindi",
    maxCapacity: 12,
    notes: "De-stressing yin yoga with targeted joint mobility and meditation.",
    status: "assigned",
  },
  {
    id: 4,
    title: "Dynamic Power Vinyasa",
    timeSlot: "7:00-8:00 pm",
    days: ["Tue", "Thu"],
    instructorId: 4,
    instructorName: "Kabir Khan",
    classType: "group",
    meetingLink: "https://zoom.us/j/9844045678",
    language: "English",
    medium: "English",
    maxCapacity: 15,
    notes: "Cardio-intensive strength and balance flow for intermediate practitioners.",
    status: "assigned",
  },
  {
    id: 5,
    title: "Weekend Sunrise Ashtanga",
    timeSlot: "6:30-7:30 am",
    days: ["Sat", "Sun"],
    instructorId: null,
    instructorName: "",
    classType: "group",
    meetingLink: "https://zoom.us/j/9855056789",
    language: "English",
    medium: "English",
    maxCapacity: 25,
    notes: "Open weekend cohort — instructor assignment pending.",
    status: "free",
  },
  {
    id: 6,
    title: "Private 1:1 Remedial Assessment",
    timeSlot: "11:00 am-12:00 pm",
    days: ["Mon", "Wed"],
    instructorId: null,
    instructorName: "",
    classType: "private",
    meetingLink: "https://meet.google.com/pri-vate-101",
    language: "Hindi",
    medium: "Hindi",
    maxCapacity: 1,
    notes: "Dedicated private 1:1 evaluation slot open for booking.",
    status: "free",
  },
];

export const DEFAULT_PAYMENT_SETTINGS = {
  upiId: "yourbusiness@upi",
  payeeName: "Your Tutoring Business",
  accountName: "Your Name",
  accountNumber: "000000000000",
  ifsc: "ABCD0123456",
  bankName: "Your Bank",
  adminWhatsApp: "+91 90000 00000",
  groupClassLinks: {
    hindi: "https://zoom.us/j/9819023456",
    english: "https://zoom.us/j/9820012345",
    default: "https://zoom.us/j/9833034567",
  },
};

export const TIMEZONE_OPTIONS = [
  { value: "Asia/Kolkata", label: "India — IST" },
  { value: "Asia/Dubai", label: "UAE — Dubai" },
  { value: "America/New_York", label: "USA — New York (ET)" },
  { value: "America/Los_Angeles", label: "USA — Los Angeles (PT)" },
  { value: "America/Chicago", label: "USA — Chicago (CT)" },
  { value: "America/Toronto", label: "Canada — Toronto" },
  { value: "Europe/London", label: "UK — London" },
  { value: "Europe/Berlin", label: "Germany — Berlin" },
  { value: "Europe/Paris", label: "France — Paris" },
  { value: "Africa/Lagos", label: "Nigeria — Lagos" },
  { value: "Asia/Singapore", label: "Singapore" },

  { value: "Asia/Tokyo", label: "Japan — Tokyo" },
  { value: "Australia/Sydney", label: "Australia — Sydney" },
  { value: "Asia/Riyadh", label: "Saudi Arabia — Riyadh" },
];

export const AVATAR_PALETTE = [
  { bg: "#FDEBDA", fg: "#B15B12" },
  { bg: "#E6E9FB", fg: "#3745A8" },
  { bg: "#EFE7FE", fg: "#6B33C9" },
  { bg: "#DFF5EA", fg: "#177A4B" },
  { bg: "#FCE4E1", fg: "#B23127" },
  { bg: "#FBEDD6", fg: "#9C6A0E" },
  { bg: "#DCEEFB", fg: "#1C6FA8" },
  { bg: "#F0EAFB", fg: "#7A3FA0" },
];

export const INITIAL_STUDENTS = [
  {
    id: 1,
    name: "Aarav Sharma",
    email: "aarav.sharma@example.com",
    phone: "+971 50 123 4567",
    classType: "private",
    groupName: null,
    instructor: "Rohan Mehta",
    country: "United Arab Emirates",
    timezone: "Asia/Dubai",
    duration: "1 Hour",
    fee: 4500,
    classTimeIST: "19:00",
    scheduleDays: [0, 1, 2, 3, 4, 5, 6],
    joiningDate: "2026-08-13",
    lastPaymentDate: "2026-08-13",
    username: "aarav.sharma",
    password: "aarav123",
  },
  {
    id: 2,
    name: "Emily Carter",
    email: "emily.carter@example.com",
    phone: "+1 917 555 0142",
    classType: "private",
    groupName: null,
    instructor: "Priya Nair",
    country: "United States",
    timezone: "America/New_York",
    duration: "1 Hour",
    fee: 6000,
    classTimeIST: "20:00",
    scheduleDays: [0, 1, 2, 3, 4, 5, 6],
    joiningDate: "2026-01-27",
    lastPaymentDate: "2026-07-27",
    username: "emily.carter",
    password: "emily123",
  },
  {
    id: 3,
    name: "Liam Johnson",
    email: "liam.johnson@example.com",
    phone: "+44 7700 900123",
    classType: "group",
    groupName: "Group A",
    instructor: "Meera Iyer",
    country: "United Kingdom",
    timezone: "Europe/London",
    duration: "1 Hour",
    fee: 2800,
    classTimeIST: "18:00",
    scheduleDays: [1, 3, 5],
    joiningDate: "2025-11-26",
    lastPaymentDate: "2026-07-26",
    username: "liam.johnson",
    password: "liam123",
  },
  {
    id: 4,
    name: "Sophia Wilson",
    email: "sophia.wilson@example.com",
    phone: "+1 416 555 0110",
    classType: "group",
    groupName: "Group A",
    instructor: "Meera Iyer",
    country: "Canada",
    timezone: "America/Toronto",
    duration: "1 Hour",
    fee: 2800,
    classTimeIST: "18:00",
    scheduleDays: [1, 3, 5],
    joiningDate: "2025-12-29",
    lastPaymentDate: "2026-06-29",
    username: "sophia.wilson",
    password: "sophia123",
  },
  {
    id: 5,
    name: "Noah Müller",
    email: "noah.mueller@example.com",
    phone: "+49 151 2345 6789",
    classType: "group",
    groupName: "Group A",
    instructor: "Meera Iyer",
    country: "Germany",
    timezone: "Europe/Berlin",
    duration: "1 Hour",
    fee: 2800,
    classTimeIST: "18:00",
    scheduleDays: [1, 3, 5],
    joiningDate: "2026-01-29",
    lastPaymentDate: "2026-07-29",
    username: "noah.mueller",
    password: "noah123",
  },
  {
    id: 6,
    name: "Haruto Sato",
    email: "haruto.sato@example.com",
    phone: "+81 90 1234 5678",
    classType: "private",
    groupName: null,
    instructor: "Kabir Khan",
    country: "Japan",
    timezone: "Asia/Tokyo",
    duration: "1 Hour",
    fee: 5500,
    classTimeIST: "16:00",
    scheduleDays: [0, 1, 2, 3, 4, 5, 6],
    joiningDate: "2026-08-20",
    lastPaymentDate: "2026-08-20",
    username: "haruto.sato",
    password: "haruto123",
  },
  {
    id: 7,
    name: "Chidinma Okafor",
    email: "chidinma.okafor@example.com",
    phone: "+234 802 123 4567",
    classType: "group",
    groupName: "Group B",
    instructor: "Kabir Khan",
    country: "Nigeria",
    timezone: "Africa/Lagos",
    duration: "1 Hour",
    fee: 2500,
    classTimeIST: "17:30",
    scheduleDays: [2, 4, 6],
    joiningDate: "2026-01-28",
    lastPaymentDate: "2026-07-28",
    username: "chidinma.okafor",
    password: "chidinma123",
  },
  {
    id: 8,
    name: "Wei Zhang",
    email: "wei.zhang@example.com",
    phone: "+65 8123 4567",
    classType: "group",
    groupName: "Group B",
    instructor: "Kabir Khan",
    country: "Singapore",
    timezone: "Asia/Singapore",
    duration: "1 Hour",
    fee: 2500,
    classTimeIST: "17:30",
    scheduleDays: [2, 4, 6],
    joiningDate: "2025-11-30",
    lastPaymentDate: "2026-07-31",
    username: "wei.zhang",
    password: "wei123",
  },
  {
    id: 9,
    name: "Olivia Brown",
    email: "olivia.brown@example.com",
    phone: "+61 412 345 678",
    classType: "private",
    groupName: null,
    instructor: "Rohan Mehta",
    country: "Australia",
    timezone: "Australia/Sydney",
    duration: "1 Hour",
    fee: 5000,
    classTimeIST: "07:00",
    scheduleDays: [0, 1, 2, 3, 4, 5, 6],
    joiningDate: "2026-08-24",
    lastPaymentDate: "2026-08-24",
    username: "olivia.brown",
    password: "olivia123",
  },
  {
    id: 10,
    name: "Ethan Davis",
    email: "ethan.davis@example.com",
    phone: "+1 213 555 0176",
    classType: "group",
    groupName: "Group B",
    instructor: "Kabir Khan",
    country: "United States",
    timezone: "America/Los_Angeles",
    duration: "1 Hour",
    fee: 2500,
    classTimeIST: "17:30",
    scheduleDays: [2, 4, 6],
    joiningDate: "2025-10-25",
    lastPaymentDate: "2026-06-25",
    username: "ethan.davis",
    password: "ethan123",
  },
];

export const INITIAL_ENQUIRIES = [
  {
    id: 1,
    name: "Priya Desai",
    gender: "Female",
    age: 34,
    heightWeight: "5'4\" / 68 kg",
    phone: "+91 98200 12345",
    email: "priya.desai@example.com",
    country: "India",
    classTypeInterest: "private",
    preferredTimings: "Mornings, 7–8 AM IST",
    demoDate: "2026-08-29",
    instructorPreference: "Female",
    reason: "Weight Loss",
    otherInfo: "Has mild knee pain, please advise on modifications.",
    message:
      "Looking for a private instructor for weight loss, prefer a female teacher.",
    status: "pending",
    submittedDate: "2026-08-24",
  },
  {
    id: 2,
    name: "James Whitfield",
    gender: "Male",
    age: 41,
    heightWeight: "5'10\" / 82 kg",
    phone: "+44 7700 900222",
    email: "james.whitfield@example.com",
    country: "United Kingdom",
    classTypeInterest: "group",
    preferredTimings: "Around 8–9 PM IST works for me",
    demoDate: "2026-08-30",
    instructorPreference: "Any",
    reason: "Regular Yoga Practice",
    otherInfo: "",
    message: "Want to join a group class for general fitness.",
    status: "in_progress",
    submittedDate: "2026-08-22",
  },
  {
    id: 3,
    name: "Fatima Al-Sayed",
    gender: "Female",
    age: 29,
    heightWeight: "5'5\" / 60 kg",
    phone: "+971 55 123 9876",
    email: "fatima.alsayed@example.com",
    country: "United Arab Emirates",
    classTypeInterest: "private",
    preferredTimings: "Late night, ~11 PM IST (I'm in Dubai)",
    demoDate: "2026-09-01",
    instructorPreference: "Female",
    reason: "Pre/Post Natal Yoga",
    otherInfo: "6 months pregnant, need a prenatal-safe routine.",
    message: "Looking for prenatal yoga with a certified instructor.",
    status: "pending",
    submittedDate: "2026-08-25",
  },
  {
    id: 4,
    name: "David Kim",
    gender: "Male",
    age: 52,
    heightWeight: "5'8\" / 90 kg",
    phone: "+1 213 555 0199",
    email: "david.kim@example.com",
    country: "United States",
    classTypeInterest: "private",
    preferredTimings: "Mornings IST (evening for me, Pacific time)",
    demoDate: "2026-08-28",
    instructorPreference: "Any",
    reason: "Yoga for Disease (Type 2 Diabetes, High BP)",
    otherInfo: "Doctor recommended yoga for blood pressure management.",
    message: "Need therapeutic yoga for diabetes and blood pressure.",
    status: "declined",
    submittedDate: "2026-08-18",
  },
  {
    id: 5,
    name: "Ananya Rao",
    gender: "Female",
    age: 24,
    heightWeight: "5'3\" / 55 kg",
    phone: "+91 90000 45612",
    email: "ananya.rao@example.com",
    country: "India",
    classTypeInterest: "group",
    preferredTimings: "Weekday evenings, 6–7 PM IST",
    demoDate: "2026-08-27",
    instructorPreference: "Any",
    reason: "Regular Yoga Practice",
    otherInfo: "",
    message: "Want to try group sessions along with a couple of friends.",
    status: "accepted",
    submittedDate: "2026-08-15",
    convertedStudentId: null,
  },
];
